'use strict';

// C++ runtime adapter: turns an uploaded .cpp into an executable. Game-agnostic —
// any judge that accepts C++ bots reuses this untouched. To add another bot
// language later, add a sibling adapter and register it in ./index.js.

const { execFile } = require('child_process');
const fs = require('fs');
const path = require('path');

const PORTABLE_BITS_HEADER = `
// Auto-generated by bot-fight-arena.
// macOS clang++ does not ship GNU's <bits/stdc++.h>, so uploaded bots that use it
// are compiled through this portable replacement header.
#include <algorithm>
#include <array>
#include <atomic>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <initializer_list>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <ostream>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
`;

function makePortableCppSource(sourcePath) {
  const original = fs.readFileSync(sourcePath, 'utf8');
  const normalized = original.replace(
    /^\s*#\s*include\s*[<\"]bits\/stdc\+\+\.h[>\"]\s*$/gm,
    PORTABLE_BITS_HEADER.trim()
  );
  if (normalized === original) return sourcePath;

  const portablePath = `${sourcePath}.portable.cpp`;
  fs.writeFileSync(portablePath, normalized);
  return portablePath;
}

function compilerCandidates(preferred) {
  const out = [];
  const add = c => {
    if (c && !out.includes(c)) out.push(c);
  };
  add(preferred);
  add(process.env.CXX);
  // Homebrew GCC on macOS is normally exposed with a versioned name.
  add('g++-15');
  add('g++-14');
  add('g++-13');
  add('g++-12');
  add('g++-11');
  add('clang++');
  add('g++');
  add('c++');
  return out;
}

function compileWith(compiler, args, options) {
  return new Promise((resolve, reject) => {
    execFile(compiler, args, { timeout: options.timeoutMs || 10000, maxBuffer: 1024 * 1024 * 8 }, (err, stdout, stderr) => {
      if (err) reject({ compiler, stdout, stderr, err });
      else resolve({ compiler, stdout, stderr });
    });
  });
}

async function compileCpp(sourcePath, outputPath, options = {}) {
  const flags = options.flags || ['-std=c++17', '-O2', '-pipe'];
  const portableSourcePath = makePortableCppSource(sourcePath);
  const args = [...flags, portableSourcePath, '-o', outputPath];
  const errors = [];

  for (const compiler of compilerCandidates(options.compiler)) {
    try {
      const result = await compileWith(compiler, args, options);
      fs.chmodSync(outputPath, 0o755);
      return { ...result, outputPath };
    } catch (e) {
      const text = e.stderr || e.stdout || e.err?.message || String(e);
      errors.push(`--- ${compiler} ---\n${text}`);
      // If a compiler executable is missing, continue. If it exists but failed
      // due to source errors, trying the next compiler is still useful on macOS
      // because GNU extensions may compile with Homebrew GCC but not clang++.
    }
  }

  throw new Error(`Compile failed for ${path.basename(sourcePath)}\n${errors.join('\n')}`);
}

module.exports = { compileCpp, makePortableCppSource };
