// Auto-generated by bot-fight-arena.
// macOS clang++ does not ship GNU's <bits/stdc++.h>, so uploaded bots that use it
// are compiled through this portable replacement header.
#include <algorithm>
#include <array>
#include <atomic>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <future>
#include <iomanip>
#include <initializer_list>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <ostream>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
using namespace std;
static const int R=10,C=17,N=170;
int myId=0, oppId=1;
struct Move{int r1,c1,r2,c2;};
struct State{array<int,N> val{}; array<int,N> own{}; bool lastPass=false;};
int id(int r,int c){return r*C+c;}
void init(State& s, vector<string> rows){for(int i=0;i<N;i++)s.own[i]=-1; for(int r=0;r<R;r++)for(int c=0;c<C;c++)s.val[id(r,c)]=rows[r][c]-'0';}
void apply(State& s, Move m, int p){ if(m.r1==-1){s.lastPass=true;return;} for(int r=m.r1;r<=m.r2;r++)for(int c=m.c1;c<=m.c2;c++){s.val[id(r,c)]=0;s.own[id(r,c)]=p;} s.lastPass=false; }
vector<Move> moves(const State& s){
  int ps[R+1][C+1]={}, nz[R+1][C+1]={};
  for(int r=0;r<R;r++)for(int c=0;c<C;c++){int v=s.val[id(r,c)]; ps[r+1][c+1]=ps[r][c+1]+ps[r+1][c]-ps[r][c]+v; nz[r+1][c+1]=nz[r][c+1]+nz[r+1][c]-nz[r][c]+(v!=0);} 
  auto sum=[&](int a[R+1][C+1],int r1,int c1,int r2,int c2){return a[r2+1][c2+1]-a[r1][c2+1]-a[r2+1][c1]+a[r1][c1];};
  vector<Move> out;
  for(int r1=0;r1<R;r1++)for(int r2=r1;r2<R;r2++)for(int c1=0;c1<C;c1++)for(int c2=c1;c2<C;c2++){
    if(sum(ps,r1,c1,r2,c2)!=10) continue;
    if(sum(nz,r1,c1,r1,c2)>0 && sum(nz,r2,c1,r2,c2)>0 && sum(nz,r1,c1,r2,c1)>0 && sum(nz,r1,c2,r2,c2)>0) out.push_back({r1,c1,r2,c2});
  }
  return out;
}
int main(){ios::sync_with_stdio(false);cin.tie(nullptr); State s; string line,cmd; while(getline(cin,line)){ if(line.empty())continue; stringstream ss(line); ss>>cmd; if(cmd=="READY"){string t;ss>>t;myId=t=="FIRST"?0:1;oppId=1-myId; cout<<"OK"<<endl;} else if(cmd=="INIT"){vector<string> rows(R); for(auto& x:rows)ss>>x; init(s,rows);} else if(cmd=="TIME"){auto m=moves(s); Move best = m.empty()?Move{-1,-1,-1,-1}:m[0]; apply(s,best,myId); cout<<best.r1<<' '<<best.c1<<' '<<best.r2<<' '<<best.c2<<endl;} else if(cmd=="OPP"){Move m; int t; ss>>m.r1>>m.c1>>m.r2>>m.c2>>t; apply(s,m,oppId);} else if(cmd=="FINISH") break; }}
